# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_auto_20151028_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='manager_method',
            field=models.CharField(blank=True, help_text='Methoed to call on ContentType.model_class().manager_name',
                                   max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='manager_name',
            field=models.CharField(default=b'objects',
                                   help_text="If using manager_method, specify the name of the manager (usually 'objects')",
                                   max_length=128),
        ),
    ]
