# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('segments', '0003_auto_20151028_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text=b'If using a ORM permission, set this and manager method', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='segment',
            name='manager_method',
            field=models.CharField(blank=True, help_text=b'Methoed to call on ContentType.model_class().objects', max_length=128, null=True),
        ),
    ]
