# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0004_auto_20170427_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segmentmembership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='segmentmembership',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='segmentmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='manager_method',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='static_ids',
        ),
        migrations.AddField(
            model_name='segment',
            name='members_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='SegmentMembership',
        ),
    ]
