# Generated by Django 3.1.2 on 2020-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0006_segment_recalculated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
